import { lazy, type ComponentType, type LazyExoticComponent } from "react";

// Route id → page component. Lazy-loaded so first paint stays fast.
export const PAGES: Record<string, LazyExoticComponent<ComponentType>> = {
  command: lazy(() => import("./CommandCenter")),
  sales: lazy(() => import("./Sales")),
  finance: lazy(() => import("./Finance")),
  transactions: lazy(() => import("./Transactions")),
  pnl: lazy(() => import("./Pnl")),
  cashflow: lazy(() => import("./CashFlow")),
  taxes: lazy(() => import("./Taxes")),
  expenses: lazy(() => import("./Expenses")),
  accounts: lazy(() => import("./Accounts")),
  payables: lazy(() => import("./Payables")),
  products: lazy(() => import("./Products")),
  inventory: lazy(() => import("./Inventory")),
  customers: lazy(() => import("./Customers")),
  marketing: lazy(() => import("./Marketing")),
  website: lazy(() => import("./Website")),
  social: lazy(() => import("./Social")),
  launches: lazy(() => import("./Launches")),
  forecasting: lazy(() => import("./Forecasting")),
  scenarios: lazy(() => import("./Scenarios")),
  trends: lazy(() => import("./Trends")),
  opportunities: lazy(() => import("./Opportunities")),
  alerts: lazy(() => import("./Alerts")),
  goals: lazy(() => import("./Goals")),
  analyst: lazy(() => import("./Analyst")),
  reports: lazy(() => import("./Reports")),
  datasources: lazy(() => import("./DataSources")),
  reconciliation: lazy(() => import("./Reconciliation")),
  decisions: lazy(() => import("./DecisionJournal")),
  settings: lazy(() => import("./Settings")),
};
